============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/bridge/code/incubyte
plugins: Faker-24.4.0, anyio-4.4.0
collected 8 items

test.py ...s..FF                                                         [100%]

=================================== FAILURES ===================================
_________________ TestAddFunction.test_handle_negative_numebr __________________

self = <test.TestAddFunction object at 0x7a1c37f1fd90>

    def test_handle_negative_numebr(self):
>       with pytest.raises(AddHandlerException, match="negative numbers not allowed -1"):
E       Failed: DID NOT RAISE <class 'main.AddHandlerException'>

test.py:38: Failed
_________________ TestAddFunction.test_handle_negative_numebrs _________________

self = <test.TestAddFunction object at 0x7a1c37f1ff70>

    def test_handle_negative_numebrs(self):
>       with pytest.raises(AddHandlerException, match="negative numbers not allowed -1,-3"):
E       Failed: DID NOT RAISE <class 'main.AddHandlerException'>

test.py:43: Failed
=========================== short test summary info ============================
FAILED test.py::TestAddFunction::test_handle_negative_numebr - Failed: DID NO...
FAILED test.py::TestAddFunction::test_handle_negative_numebrs - Failed: DID N...
==================== 2 failed, 5 passed, 1 skipped in 0.04s ====================
